'use client'

import Link from 'next/link'
import styles from './LandingPage.module.css'

export default function LandingPage() {
  return (
    <div className={styles.container}>
      {/* Navigation */}
      <nav className={styles.nav}>
        <div className={styles.navContent}>
          <div className={styles.logo}>PathMind</div>
          <div className={styles.navLinks}>
            <Link href="/login" className={styles.navLink}>
              Sign In
            </Link>
            <Link href="/signup" className={styles.navButton}>
              Get Started
            </Link>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <section className={styles.hero}>
        <div className={styles.heroContent}>
          <h1 className={styles.heroTitle}>
            Learn Smarter, Not Harder
          </h1>
          <p className={styles.heroSubtitle}>
            PathMind creates personalized AI-powered learning roadmaps that show you
            <strong> what to learn, in what order, and why</strong>. No more random tutorials.
          </p>
          <div className={styles.heroButtons}>
            <Link href="/signup" className={styles.primaryButton}>
              Start Learning Free
            </Link>
            <Link href="/login" className={styles.secondaryButton}>
              Sign In
            </Link>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className={styles.features}>
        <div className={styles.featuresContent}>
          <h2 className={styles.sectionTitle}>Why PathMind?</h2>
          <div className={styles.featuresGrid}>
            <div className={styles.featureCard}>
              <div className={styles.featureIcon}>🗺️</div>
              <h3 className={styles.featureTitle}>Structured Roadmaps</h3>
              <p className={styles.featureDescription}>
                Visual flowcharts show dependencies and learning paths, not just a list of topics.
              </p>
            </div>
            <div className={styles.featureCard}>
              <div className={styles.featureIcon}>🤖</div>
              <h3 className={styles.featureTitle}>AI-Powered</h3>
              <p className={styles.featureDescription}>
                Get personalized learning paths generated by AI based on your specific goals.
              </p>
            </div>
            <div className={styles.featureCard}>
              <div className={styles.featureIcon}>💡</div>
              <h3 className={styles.featureTitle}>Understand Why</h3>
              <p className={styles.featureDescription}>
                AI assistant explains each topic, why it matters, and how it connects to your goal.
              </p>
            </div>
            <div className={styles.featureCard}>
              <div className={styles.featureIcon}>📚</div>
              <h3 className={styles.featureTitle}>Curated Resources</h3>
              <p className={styles.featureDescription}>
                Access documentation, videos, and tutorials directly from each topic node.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className={styles.cta}>
        <div className={styles.ctaContent}>
          <h2 className={styles.ctaTitle}>Ready to Start Your Learning Journey?</h2>
          <p className={styles.ctaSubtitle}>
            Join PathMind today and discover the most efficient path to your goals.
          </p>
          <Link href="/signup" className={styles.ctaButton}>
            Get Started Free
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer className={styles.footer}>
        <div className={styles.footerContent}>
          <p>&copy; 2024 PathMind. All rights reserved.</p>
        </div>
      </footer>
    </div>
  )
}

