'use client'

import styles from './Features.module.css'

const features = [
  {
    icon: '',
    title: 'Structured Roadmaps',
    description: 'Visual flowcharts show dependencies and learning paths, not just a list of topics. Understand the connections between concepts.',
    gradient: 'linear-gradient(135deg, #8a2be2 0%, #4a00e0 100%)'
  },
  {
    icon: '',
    title: 'AI-Powered',
    description: 'Get personalized learning paths generated by AI based on your specific goals. Tailored to your experience level and objectives.',
    gradient: 'linear-gradient(135deg, #4a00e0 0%, #6a0dad 100%)'
  },
  {
    icon: '',
    title: 'Understand Why',
    description: 'AI assistant explains each topic, why it matters, and how it connects to your goal. Learn with purpose, not just memorization.',
    gradient: 'linear-gradient(135deg, #6a0dad 0%, #8a2be2 100%)'
  },
  {
    icon: '',
    title: 'Curated Resources',
    description: 'Access documentation, videos, and tutorials directly from each topic node. All resources vetted and organized for optimal learning.',
    gradient: 'linear-gradient(135deg, #8a2be2 0%, #4a00e0 100%)'
  }
]

export default function Features() {
  return (
    <section id="features" className={styles.features}>
      <div className={styles.featuresContent}>
        <div className={styles.sectionHeader}>
          <h2 className={styles.sectionTitle}>
            <span className={styles.sectionTitleText}>Why PathMind?</span>
            <span className={styles.sectionTitleGlow}>Why PathMind?</span>
          </h2>
          <p className={styles.sectionSubtitle}>
            Everything you need to learn efficiently and effectively
          </p>
        </div>
        
        <div className={styles.featuresGrid}>
          {features.map((feature, index) => (
            <div key={index} className={styles.featureCard}>
              <div className={styles.featureCardGlow} style={{ background: feature.gradient }}></div>
              <div className={styles.featureIconWrapper}>
                <div className={styles.featureIcon} style={{ background: feature.gradient }}>
                  {feature.icon}
                </div>
              </div>
              <h3 className={styles.featureTitle}>{feature.title}</h3>
              <p className={styles.featureDescription}>{feature.description}</p>
              <div className={styles.featureCardBorder} style={{ background: feature.gradient }}></div>
            </div>
          ))}
        </div>
      </div>
    </section>
  )
}

